<?php

namespace app\telegram\controller;

use think\Controller;

class Base extends Controller
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }
}